### ISSUE TITLE
Error with NodeJS 10

### ISSUE THREAD

**Issue by larskn** [typescript-eslint/tslint-to-eslint-config#260]
### Bug or missing documentation (depends)

-   `tslint-to-eslint-config` version: 0.2.10
-   Node version: 10.16.3
-   OS: Windows 10 64-Bit

#### Actual Behavior

When running `npx tslint-to-eslint-config` with nodejs 10.16.3 installed, the following error occurs.

> TypeError: [[rawConfiguration.extends],[reportedConfiguration.extends]].flat is not a function
> at exports.findTSLintConfiguration [...]

After updating to 12.13.0 everything runs fine.

Is it intentional that only Node >=12 is supported? If yes, it might be useful to document it in the readme to prevent future bug reports.

**Comment by JoshuaKGoldberg** [comment]
Aha, yes, Node 12 is required. Thanks for reporting @larskn ! I'll add it to the README.md right away.
