### ISSUE TITLE
TypeError: (0 , glob_1.default) is not a function

### ISSUE THREAD

**Issue by andreidiaconescu** [typescript-eslint/tslint-to-eslint-config#1817]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.14.1
-   ESLint version: 8.54.0
-   Node version: 20.9.0

#### Actual Behavior

`sudo npx tslint-to-eslint-config --comments`

and i get the output including error
```
✨ 114 rules replaced with their ESLint equivalents. ✨

❗ 7 ESLint rules behave differently from their TSLint counterparts ❗
  Check ./tslint-to-eslint-config.log for details.
❌ 1 error running tslint-to-eslint: ❌
  TypeError: (0 , glob_1.default) is not a function
    at /mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/adapters/globAsync.js:10:28
    at new Promise (<anonymous>:null:null)
    at globAsync (/mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/adapters/globAsync.js:9:12)
    at Array.map (<anonymous>:null:null)
    at extractGlobPaths (/mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/converters/comments/extractGlobPaths.js:11:102)
    at convertComments (/mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/converters/comments/convertComments.js:28:49)
    at tryConvertConfig (/mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/cli/runCli.js:64:18)
    at runCli (/mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/cli/runCli.js:50:24)
    at Object.main (/mnt/otherLinuxPartition/var/www/kickstart/api/node_modules/tslint-to-eslint-config/src/cli/main.js:11:30)
```
 - the code comments are not actually modified
 - i got stuck

#### Expected Behavior
 The command 
`sudo npx tslint-to-eslint-config --comments`
should work and replace tslint comments with eslint comments.

**Comment by hyperupcall** [comment]
This was introduced in c2572c173d13c850fd35e761bb7ecdc239f4a913. v10 [stopped supporting default export](https://github.com/isaacs/node-glob/blob/97611cd366e5906a4c58df3f5214af843b0a5e63/changelog.md?plain=1#L18)

**Comment by hyperupcall** [comment]
I filed a PR to fix this. As a workaround, you can run with the following:

```sh
npx tslint-to-eslint-config@v2.14.0 --comments
```

**Comment by andreidiaconescu** [comment]
hello,
thank you,
when i run
`npx tslint-to-eslint-config@v2.14.0 --comments`
i get error:
```
✨ 114 rules replaced with their ESLint equivalents. ✨

❗ 7 ESLint rules behave differently from their TSLint counterparts ❗
  Check ./tslint-to-eslint-config.log for details.
❌ 2 errors running tslint-to-eslint: ❌
  Error: EISDIR: illegal operation on a directory, read

  Error: EISDIR: illegal operation on a directory, read

```

**Comment by JoshuaKGoldberg** [comment]
https://www.npmjs.com/package/tslint-to-eslint-config/v/2.14.3 should include the fix now. 👍
